name: 'Ruby'

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-gemspec:
    name: "Build Gem"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: 'actions/checkout@v4'
      - name: "Setup Ruby"
        uses: 'ruby/setup-ruby@v1'
      - name: "Build Gem"
        run: gem build .gemspec
      - name: "Test Binary"
        run: ruby bin/puppy-fetch

